version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: employees_db
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - employee_net

  spark:
    build: ./spark
    container_name: spark_app
    depends_on:
      - postgres
    volumes:
      - ./data:/opt/data
      - ./logs:/opt/logs
    networks:
      - employee_net

networks:
  employee_net:
    driver: bridge
